### ISSUE TITLE
尊敬的作者，您好，想求一份polar fuzz libmodbus的代码,感激不尽！

### ISSUE THREAD

**Issue by 16201535wangshenyu** [fouzhe/Polar-Fuzz#2]
邮箱：1337116052@qq.com

**Comment by fouzhe** [comment]
Thanks for your attention!
We used the demo in the [libmodbus/tests](https://github.com/stephane/libmodbus/tree/master/tests) as the under-test-program and used [preeny](https://github.com/zardus/preeny) to support server fuzzing (this [blog](https://www.secpulse.com/archives/71903.html) gives a simple usage).
Then, to run with Polar, you need to provide the function code specification (`-j` option for Polar) and instrument the code with `__POLAR_INS((1<<16)+ID);` manually  because the function code identification module of Polar is not open-source :P. For more details, you can refer to the [demo](https://github.com/fouzhe/Polar-Fuzz/tree/master/Polar-AFL/demo).
